#!/usr/bin/env bash
# Requirements:

# Install nginx on your web-01
# server
# Nginx should be listening on port 80

# Update package list and install nginx
sudo apt-get -y update
sudo apt --fix-broken install
sudo apt-get install -y nginx

# Ensure nginx is listening to port 80
sudo ufw allow 'Nginx HTTP'

# Set up the default page
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (without using systemctl)
sudo service nginx restart
