#!/usr/bin/env bash
# Requirements:

# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# Return a Hello World string


# Update package list and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Give the user ownership

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Ensure nginx is listening to port 80
ufw allow 'Nginx HTTP'

# Set up the default page
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (without using systemctl)
sudo service nginx restart
