#!/usr/bin/env bash
# Install nginx on your web-01server
# Nginx should be listening on port 80


# Update package list and install ngix
sudo apt-get update -y
sudo apt-get install -y nginx

# start nginx service
sudo service nginx start

# Ensure nginx is listening on port 80
sudo ufw allow 'Nginx HTTP'

# Give the user ownership 
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Set up the default page
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
# Configure a new server block for redirection
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Enable the new site configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

#Restart nginx 
sudo service nginx restart
