#!/usr/bin/env bash
#Bash script that displays listening ports:
#That only shows listening sockets
#That shows the PID and name of the program to which each socket belongs

if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
