#!/usr/bin/env bash
# Bash script that configures Nginx to listen to port 80  IPv4 IPs

# configure Nginx to listen to port 80
ln - sf /etc/nginx/sites-available/default/etc/nginx/sites-enabled/default

# nginx restart
service nginx restart
