#!/usr/bin/env bash
#Bash script that configures Nginx to listen to port 80  IPv4 IPs


#remove default nginx file
rm /etc/nginx/sites-available/default

#cnfigure Nginx to listen to port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#nginx restart
service nginx restart
