#!/usr/bin/env bash
#Story of the passwd
while IFS= read -r contents; do
	username=$(echo "$contents" | cut -f 1 -d ':')
	password=$(echo "$contents" | cut -f 2 -d ':')
	uid=$(echo "$contents" | cut -f 3 -d ':')
	gid=$(echo "$contents" | cut -f 4 -d ':')
	user_info=$(echo "$contents" | cut -f 5 -d ':')
	home=$(echo "$contents" | cut -f 6 -d ':')
	command=$(echo "$contents" | cut -f 7 -d ':')

	echo -n "The user $username is part of the $gid gang, "
	echo -n "lives in $home and rides $command."
	echo -n "$uid's place is protected by the passcode $password, "
	echo -n "more info about the user here: $user_info"
	echo	
done < /etc/passwd
